### ISSUE TITLE
Error on first install

### ISSUE THREAD

**Issue by digitorum** [antfu/vue-demi#3]
Catch error on first install every time...

OS:
- [ ] linux mint (Linux DRB31-U 4.15.0-91-generic #92-Ubuntu)
- [ ] windows 10 home

```
yarn add vue-demi
yarn add v1.21.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /home/echo/ui-demi/node_modules/vue-demi: Command failed.
Exit code: 1
Command: node ./scripts/postinstall.js
Arguments: 
Directory: /home/echo/ui-demi/node_modules/vue-demi
Output:
yarn add v1.21.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ @vue/composition-api@1.0.0-beta.6
info All dependencies
└─ @vue/composition-api@1.0.0-beta.6
Done in 13.29s.
internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/echo/ui-demi/node_modules/vue-demi/lib/index.cjs.js'
    at Object.openSync (fs.js:440:3)
    at Object.writeFileSync (fs.js:1265:35)
    at switchVersion (/home/echo/ui-demi/node_modules/vue-demi/scripts/postinstall.js:31:6)
    at Object.<anonymous> (/home/echo/ui-demi/node_modules/vue-demi/scripts/postinstall.js:46:3)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/echo/ui-demi/node_modules/vue-demi/lib/index.cjs.js'
}
```

**Comment by antfu** [comment]
Should be fixed in v0.2.0
