### ISSUE TITLE
Error: [vue-composition-api] must call Vue.use(VueCompositionAPI) before using any function in typescripts

### ISSUE THREAD

**Issue by ChrisMichaelPerezSantiago** [antfu/vue-demi#6]
Hello,

I'm having trouble using your library to implement some functions in `typescript`. Is showing me the message

```shell
"Error: [vue-composition-api] must call Vue.use (VueCompositionAPI) before using any function."
```
I leave below the error output.
I will appreciate your help and your prompt response.!!

```ts
import {ref, reactive, UnwrapRef, Ref } from 'vue-demi';

export function fxReactive<T extends object>(obj: T): UnwrapRef<T> {
  return reactive(obj);
}

const fx = fxReactive({
  data: []
});

console.log(fx.data);
```

**devDependecies**

```json
"@vue/composition-api": "^1.0.0-beta.1",
"vue": "^2.6.11"
```

**dependecies**
```json
"vue-demi": "latest"
```

**error**
```shell
C:\Users\c\Desktop\reactivefx\node_modules\@vue\composition-api\dist\vue-composition-api.common.js:43
        throw new Error("[vue-composition-api] " + msg);
              ^
Error: [vue-composition-api] must call Vue.use(VueCompositionAPI) before using any function.
    at assert (C:\Users\c\Desktop\reactivefx\node_modules\@vue\composition-api\dist\vue-composition-api.common.js:43:15)
    at getVueConstructor (C:\Users\c\Desktop\reactivefx\node_modules\@vue\composition-api\dist\vue-composition-api.common.js:83:9)
    at observe (C:\Users\c\Desktop\reactivefx\node_modules\@vue\composition-api\dist\vue-composition-api.common.js:470:15)
    at Function.reactive (C:\Users\c\Desktop\reactivefx\node_modules\@vue\composition-api\dist\vue-composition-api.common.js:595:20)
    at fxReactive (C:\Users\c\Desktop\reactivefx\src\index.ts:6:10)
    at Object.<anonymous> (C:\Users\c\Desktop\reactivefx\src\index.ts:9:12)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Module.m._compile (C:\Users\c\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:473:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\c\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:476:12)
```

**Comment by antfu** [comment]
@ChrisMichaelPerezSantiago Can try to remove `@vue/composition-api` in your dev deps and run the install again. It might be some version conflicts in your env. And, can you find the installed version of `vue-demi` in your lock file or `node_modules` so I can have a better sense of where is breaking? Thanks

**Comment by ChrisMichaelPerezSantiago** [comment]
@antfu ,

I removed the `@vue/composition-api` package and then also removed the `node_module` along with the` package-lock`.


Then I did `npm instal`l, this generated the `node_module` again.
When running the program it shows me the same error that I showed you previously.


But I could see that in the package-lock they are registered:

```json
  "vue": {
       "version": "2.6.12",
       "resolved": "https://registry.npmjs.org/vue/-/vue-2.6.12.tgz",
       "integrity": "sha512-uhmLFETqPPNyuLLbsKz6ioJ4q7AZHzD8ZVFNATNyICSZouqP2Sz0rotWQC8UNBF6VGSCs5abnKJoStA6JbCbfg ==",
       "dev": true
     },
     "vue-demi": {
       "version": "0.2.0",
       "resolved": "https://registry.npmjs.org/vue-demi/-/vue-demi-0.2.0.tgz",
       "integrity": "sha512-EbB3UxYacKwORuey3VShOO0IJ + h8W2aq6v574m0XRMYrVOH2TkfO660gm7ZfNVHKHK4leNzVkAGGIfYDxrAFPg ==",
       "requires": {
         "@ vue / composition-api": "> = 1.0.0-beta.1"
       }
     },
```

And in the node_module the package is also registered
`@vue/composition-api` and `vue`

**Comment by ChrisMichaelPerezSantiago** [comment]
Here is the [repo](https://github.com/ChrisMichaelPerezSantiago/reactivefx)

To run the project you just have to write

```shell
npm run start
```

**Comment by antfu** [comment]
I don't think you can use `@vue/composition-api` in bare node environment. You might need to setup up a Vue project to test out your plugin.

**Comment by ChrisMichaelPerezSantiago** [comment]
@antfu ,

Any starter template that you recommend?

**Comment by antfu** [comment]
Planned to make one but didn't get time to do so. You might want to check the simple demo in the `examples` for now.
